version: 2
updates:
- package-ecosystem: npm
  directory: "/ui"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@date-io/date-fns"
    versions:
    - "> 1.3.13"
  - dependency-name: react-virtualized
    versions:
    - "> 9.21.1"
